import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { report } = body

    if (!report) {
      return NextResponse.json(
        { error: 'Report data is required', message: 'No report data provided' },
        { status: 400 }
      )
    }

    if (!report.title || !report.type || !report.generatedAt) {
      return NextResponse.json(
        { error: 'Invalid report data', message: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Create PDF with options that work in serverless environments
    // Using Courier font which is most reliably built-in and doesn't require external files
    // Setting font in constructor to prevent PDFKit from trying to load default Helvetica font
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      autoFirstPage: true,
      font: 'Courier', // Set font in constructor to prevent loading external font files
    })

    const chunks: Buffer[] = []
    let pageNumber = 1
    
    doc.on('data', (chunk) => chunks.push(chunk))

    // Add footer function that will be called on each page
    const addFooter = (currentPageNumber: number) => {
      const pageHeight = doc.page.height
      const pageWidth = doc.page.width
      doc
        .fontSize(10)
        .font('Courier')
        .fillColor('#999999')
        .text(
          `Generated by Mongers Rugby Club Management System${currentPageNumber > 1 ? ` - Page ${currentPageNumber}` : ''}`,
          50,
          pageHeight - 30,
          { align: 'center', width: pageWidth - 100 }
        )
    }

    // Set up footer for subsequent pages (pageAdded fires when a new page is added)
    doc.on('pageAdded', () => {
      pageNumber++
      addFooter(pageNumber)
    })

    // Header - using Courier built-in font
    doc
      .fontSize(24)
      .font('Courier-Bold')
      .fillColor('#1a1a1a')
      .text('Mongers Rugby Club', 50, 50, { align: 'center' })
    
    doc
      .fontSize(16)
      .font('Courier')
      .fillColor('#666666')
      .text('Official Report', 50, 80, { align: 'center' })

    // Report Title
    doc
      .fontSize(20)
      .font('Courier-Bold')
      .fillColor('#1a1a1a')
      .text(report.title, 50, 120, { align: 'center' })

    // Report Details
    let yPos = 170
    doc
      .fontSize(12)
      .font('Courier')
      .fillColor('#333333')
      .text(`Report Type: ${report.type.charAt(0).toUpperCase() + report.type.slice(1)}`, 50, yPos)
    
    yPos += 20
    doc.text(`Date Range: ${report.dateRange}`, 50, yPos)
    
    yPos += 20
    doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, 50, yPos)

    // Add a line separator
    yPos += 30
    doc
      .moveTo(50, yPos)
      .lineTo(550, yPos)
      .strokeColor('#cccccc')
      .lineWidth(1)
      .stroke()

    // Report Content
    yPos += 30
    if (report.data) {
      doc
        .fontSize(14)
        .font('Courier-Bold')
        .fillColor('#1a1a1a')
        .text('Report Summary', 50, yPos)
      
      yPos += 25
      doc
        .fontSize(11)
        .font('Courier')
        .fillColor('#333333')
        .text(JSON.stringify(report.data, null, 2), 50, yPos, {
          width: 500,
          align: 'left',
        })
    } else {
      doc
        .fontSize(12)
        .font('Courier')
        .fillColor('#666666')
        .text('This report contains detailed information about the selected category.', 50, yPos, {
          width: 500,
          align: 'left',
        })
    }

    // Add footer to first page
    addFooter(1)

    // Generate PDF buffer
    return new Promise<NextResponse>((resolve, reject) => {
      let hasResolved = false
      
      doc.on('end', () => {
        if (hasResolved) return
        hasResolved = true
        
        try {
          const pdfBuffer = Buffer.concat(chunks)
          resolve(
            new NextResponse(pdfBuffer, {
              headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf"`,
              },
            })
          )
        } catch (err: any) {
          reject(new Error(`Failed to create PDF buffer: ${err.message}`))
        }
      })
      
      doc.on('error', (err: Error) => {
        if (hasResolved) return
        hasResolved = true
        reject(new Error(`PDF generation error: ${err.message}`))
      })
      
      try {
        doc.end()
      } catch (err: any) {
        if (hasResolved) return
        hasResolved = true
        reject(new Error(`Failed to finalize PDF: ${err.message}`))
      }
    })
  } catch (error: any) {
    console.error('Error generating PDF:', error)
    const errorMessage = error?.message || 'Unknown error occurred'
    const errorStack = error?.stack || ''
    
    return NextResponse.json(
      { 
        error: 'Failed to generate PDF', 
        message: errorMessage,
        details: process.env.NODE_ENV === 'development' ? errorStack : undefined
      },
      { status: 500 }
    )
  }
}

