import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { report } = body

    // Create PDF
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    })

    const chunks: Buffer[] = []
    
    doc.on('data', (chunk) => chunks.push(chunk))

    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor('#1a1a1a')
      .text('Mongers Rugby Club', 50, 50, { align: 'center' })
    
    doc
      .fontSize(16)
      .font('Helvetica')
      .fillColor('#666666')
      .text('Official Report', 50, 80, { align: 'center' })

    // Report Title
    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .fillColor('#1a1a1a')
      .text(report.title, 50, 120, { align: 'center' })

    // Report Details
    let yPos = 170
    doc
      .fontSize(12)
      .font('Helvetica')
      .fillColor('#333333')
      .text(`Report Type: ${report.type.charAt(0).toUpperCase() + report.type.slice(1)}`, 50, yPos)
    
    yPos += 20
    doc.text(`Date Range: ${report.dateRange}`, 50, yPos)
    
    yPos += 20
    doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, 50, yPos)

    // Add a line separator
    yPos += 30
    doc
      .moveTo(50, yPos)
      .lineTo(550, yPos)
      .strokeColor('#cccccc')
      .lineWidth(1)
      .stroke()

    // Report Content
    yPos += 30
    if (report.data) {
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#1a1a1a')
        .text('Report Summary', 50, yPos)
      
      yPos += 25
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor('#333333')
        .text(JSON.stringify(report.data, null, 2), 50, yPos, {
          width: 500,
          align: 'left',
        })
    } else {
      doc
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#666666')
        .text('This report contains detailed information about the selected category.', 50, yPos, {
          width: 500,
          align: 'left',
        })
    }

    // Footer
    const pageHeight = doc.page.height
    const pageWidth = doc.page.width
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#999999')
      .text(
        `Generated by Mongers Rugby Club Management System - Page ${doc.page.number}`,
        50,
        pageHeight - 30,
        { align: 'center', width: pageWidth - 100 }
      )

    // Generate PDF buffer
    return new Promise<NextResponse>((resolve, reject) => {
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks)
        resolve(
          new NextResponse(pdfBuffer, {
            headers: {
              'Content-Type': 'application/pdf',
              'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf"`,
            },
          })
        )
      })
      doc.on('error', reject)
      doc.end()
    })
  } catch (error: any) {
    console.error('Error generating PDF:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF', message: error.message },
      { status: 500 }
    )
  }
}

